workflows:
  ios-workflow:
    name: LiA iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    working_directory: ./
    environment:
      groups:
        - fastlane_credentials
    scripts:
      - name: Run build script
        script: |
          #!/bin/sh
          npm_config_yes=true npx rnbuilder@latest build --target ios --branch staging --env staging --branch staging --distribute firebase --testersIos liatesters --firebase true
    