

const CONNECTION = "connection";

// ONLINE USERS
const SSC_ONLINE_USERS = "SSC_ONLINE_USERS";
const SSC_OFFLINE_USERS = "SSC_OFFLINE_USERS";


const SSC_USER_CONNECT = "SSC_USER_CONNECT";
const SSC_USER_DISCONNECT = "SSC_USER_DISCONNECT";

const SSC_ROOM_LISTS = "SSC_ROOM_LISTS";
const CSS_SEND_MESSAGE = "CSS_SEND_MESSAGE";
const SSC_SEND_LIST_LATEST_MESSAGES = "SSC_SEND_LIST_LATEST_MESSAGES";
const SSC_SEND_NEW_MESSAGE = "SSC_SEND_NEW_MESSAGE";
const TEST = "test"

// CHATTING
const CSS_USER_TYPING = "CSS_USER_TYPING";
const SSC_USER_TYPING = "SSC_USER_TYPING";
const CSS_USER_SEEN_MESSAGE = "CSS_USER_SEEN_MESSAGE";

const CSS_PARTNER_TYPING = "CSS_PARTNER_TYPING";

const CSS_PARTNER_SEEN_MESSAGE = "CSS_PARTNER_SEEN_MESSAGE";
const SSC_PARTNER_SEEN_MESSAGE = "SSC_PARTNER_SEEN_MESSAGE";


const SSC_USER_SEEN_MESSAGE = "SSC_USER_SEEN_MESSAGE";
const SSC_USER_WITHDRAW_MESSAGE = "SSC_USER_WITHDRAW_MESSAGE";
const SSC_PARTNER_MESSAGE_UPDATE="SSC_PARTNER_MESSAGE_UPDATE"
const SSC_PARTNER_CREATE_REVIEW_MESSAGE="SSC_PARTNER_CREATE_REVIEW_MESSAGE"



const SSC_NOTIFICATION = "SSC_NOTIFICATION"

// POST 
const CSS_PARTNER_POST_JOIN_ROOM = "CSS_PARTNER_POST_JOIN_ROOM"
const CSS_PARTNER_POST_LEFT_ROOM = "CSS_PARTNER_POST_LEFT_ROOM"
const SSC_PARTNER_POST_COMMENT_CREATE = "SSC_PARTNER_POST_COMMENT_CREATE"
const SSC_PARTNER_POST_COMMENT_UPDATE = "SSC_PARTNER_POST_COMMENT_UPDATE"
const SSC_PARTNER_POST_COMMENT_DELETE = "SSC_PARTNER_POST_COMMENT_DELETE"

const SSC_PARTNER_POST_CREATE = "SSC_PARTNER_POST_CREATE"
const SSC_PARTNER_POST_UPDATE = "SSC_PARTNER_POST_UPDATE"
const SSC_PARTNER_POST_DELETE = "SSC_PARTNER_POST_DELETE"



const SSC_PARTNER_NOTIFICATION_CREATE="SSC_PARTNER_NOTIFICATION_CREATE"

export {
    SSC_PARTNER_POST_CREATE,
    SSC_PARTNER_POST_UPDATE,
    SSC_PARTNER_POST_DELETE,
    SSC_PARTNER_POST_COMMENT_DELETE,
    SSC_PARTNER_POST_COMMENT_UPDATE,
    SSC_PARTNER_POST_COMMENT_CREATE,
    CSS_PARTNER_POST_LEFT_ROOM,
    CSS_PARTNER_POST_JOIN_ROOM,
    SSC_PARTNER_SEEN_MESSAGE,
    CSS_PARTNER_SEEN_MESSAGE,
    CONNECTION,
    SSC_ONLINE_USERS,
    SSC_USER_WITHDRAW_MESSAGE,
    SSC_OFFLINE_USERS,
    SSC_USER_CONNECT,
    SSC_USER_DISCONNECT,
    SSC_ROOM_LISTS,
    CSS_SEND_MESSAGE,
    SSC_SEND_LIST_LATEST_MESSAGES,
    SSC_SEND_NEW_MESSAGE,
    TEST, CSS_USER_TYPING,
    SSC_USER_TYPING,
    CSS_USER_SEEN_MESSAGE,
    SSC_USER_SEEN_MESSAGE,
    SSC_NOTIFICATION,
    SSC_PARTNER_NOTIFICATION_CREATE,
    SSC_PARTNER_MESSAGE_UPDATE,
    SSC_PARTNER_CREATE_REVIEW_MESSAGE,
    CSS_PARTNER_TYPING
};
