const FROM_GROUP_CHAT_ID = 'FROM_GROUP_CHAT_ID'
const FROM_RECEIVER_ID = 'FROM_RECEIVER_ID'

// EVENT
const NEW_MESSAGE = 'NEW_MESSAGE'
const ADD_POST_COMMENT_POST_AUTHOR = "ADD_POST_COMMENT_POST_AUTHOR"
const ADD_POST_COMMENT = "ADD_POST_COMMENT"
const CREATE_POST = "CREATE_POST"
const UPDATE_TASK = "UPDATE_TASK"
const ADD_TASK_COMMENT = "ADD_TASK_COMMENT"

export{
    FROM_GROUP_CHAT_ID,
    FROM_RECEIVER_ID,
    NEW_MESSAGE,
    ADD_POST_COMMENT_POST_AUTHOR,
    CREATE_POST,
    UPDATE_TASK,
    ADD_TASK_COMMENT,
    ADD_POST_COMMENT
}