# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

import "/Users/tuanluong/Workspace/react-native/rnbuider/fastlane/Fastfile"

# import_from_git(
#   url: "https://github.com/r0b0t3d/rnbuider.git", # The URL of the repository to import the Fastfile from.
#   branch: "main", # The branch to checkout on the repository
#   path: "fastlane/Fastfile", # The path of the Fastfile in the repository
#   # version: "~> 1.0.0" # The version to checkout on the repository. Optimistic match operator can be used to select the latest version within constraints.
#   cache_path: "~/.cache/fastlane/imported"
# )

