import { Branch } from "./branch";
import { FileAvatar, Timestamp } from "./common";
import { Doctor } from "./doctor";
import { Practitioner } from "./practitioner";
import { Review } from "./review";
import { Service } from "./serviceGroup";

export type OrderService = {
  serviceCodeGroup: string[];
  originalPrice: number;
  finalPrice: number;
  currentProgress: number;
  totalProgress: number;
  isConfirm: boolean;
  isComplete: boolean;
  startTreatmentAt: string;
  startTreatmentDetailId: string;
  completeTreatmentAt: string;
  status: string;
  treatmentStatusCodeArr: string[];
  hashTagCodeArr: string[];
  isActive: boolean;
  isDelete: boolean;
  _id: string;
  orderId: string;
  serviceCode: string;
  partnerId: string;
  code: string;
  serviceName: string;
  userCreate: string;
  options: any[];
  created: string;
  updated: string;
  __v: 0;
  userUpdate: string;
  id: string;
  service: Service;
};

export type ServiceTreatment = {
  progress: number;
  supporterIdArr: string[];
  description: string;
  completeAt: string;
  status: "COMPLETE";
  needCare: boolean;
  treatmentStatusCodeArr: string[];
  hashTagCodeArr: string[];
  isActive: boolean;
  isDelete: boolean;
  _id: string;
  orderServiceId: string;
  treatmentQueueId: string;
  code: string;
  serviceCode: string;
  serviceName: string;
  branchCode: string;
  partnerId: string;
  treatmentDoctorCode: string;
  doctorId: string;
  bookingId: string;
  userCreate: string;
  __v: 0;
  userUpdate: string;
  practitioner: Practitioner;
  treatmentStatusArr: string[];
  id: string;
  serviceCodeGroup: string[];
  imageAfterTreatment: FileAvatar[];
  imageBeforeTreatment: FileAvatar[];
  service: Service;
  orderService: OrderService;
  branch: Branch;
  doctor: Doctor;
  review: Review;
} & Timestamp;
