import { FileAvatar, Timestamp } from "./common";
import { PartnerPhone } from "./partner";

export type UserProfile = {
  _id: string;
  code: string;
  fileAvatar: FileAvatar;
  firstName: string;
  id: string;
  lastName: string;
  avatarTemp: string;
  email: string[];
  partnerType: "personal";
  gender: "female";
  description: string;
  profession: string;
  nationality: string;
  ethnicity: string;
  assignedUsers: any[];
  sourceCodeArr: any[];
  groupCodeArr: any[];
  labelCodeArr: any[];
  interestedServiceCodeArr: any[];
  facebook: string;
  instagram: string;
  zalo: string;
  importId: string;
  duplicateImportIdArr: any[];
  isOfficial: boolean;
  isCollaborator: boolean;
  collaboratorCode: string;
  levelCode: "BRONZE";
  liaPoint: number;
  isActive: boolean;
  userCreate: string;
  userUpdate: string;
  isDelete: boolean;
  isSeed: boolean;
  name: string;
  address: string;
  birthday: string;
  platformSources: any[];
  slug: string;
  __v: string;
  accountId: string;
  firstTreatmentAt: string;
  interestedServiceArr: any[];
  level: string;
  phone: PartnerPhone[];
} & Timestamp;
